### PR TITLE
user-interface done

### PR DESCRIPTION
**Pull request by geraldgsh**

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
### Hi @geraldgsh  and @webmarkyn  :wave:  
Great work implementing the user interface for the game.
**Note:** _In this milestone, not everything must work. The purpose of this milestone to make sure you had thought about game implementation details before starting to implement logic. Inline comments are allowed._

Let's implement a few requirements before we make this as done.

 **[REQUIRED]** 
* The game tells which player turn it is.
* The game informs player if selected move is invalid.
* The game informs player if selected move is a winning or a draw move.
* The game repeats all actions for next player's move.

The loop should be terminated after a winning move or draw.

**[OPTIONAL]**
* The game ask players for their names.

**After implementing the changes, submit another request for review.**

_Happy Coding :computer: 
Reviewed by: **Simon Wathigo**_

**Comment by geraldgsh** [comment]
@wathigo Amendments have been done in accordance with your suggestion.  A separate code review will be submitted.

**Review by wathigo — APPROVED** [review]
### Hi @geraldgsh  and @webmarkyn  :wave:  
This looks good now.

**Go ahead and implement the next milestone.**

_Happy Coding :computer: 
Reviewed by: **Simon Wathigo**_

**Comment by geraldgsh** [comment]
Thanks @wathigo. We'll move on to the next milestone.

**Pull request merged**
